### ISSUE TITLE
warmup

### ISSUE THREAD

**Issue by leliel12** [Gaiana/nirdust#1]
- [x] Pasar todos ipynb y el README a una carpeta `draft`
- [x] `nirdust.py` <<< archivo con codigo relevante
- [x] Agregar antes que nada el .gitignore
- [x] `test_nirdust.py`
- [x] Agregar LICENCE
- [x] tox.ini py38, style, coverage (al 80%)
- [x] Readme: Que operaciones vas a querer en nirdust, 

```python
class NirdustSpectrum(Spectrum1d):
    ...

spectre = NirdustSpectrum(t=...)

spectre.predict(...)

```

**Comment by BrunoSanchez** [comment]
I think that the API could do stuff like this:

```python
from astropy.io import ascii
from nirdust import NirdustSpectrum

data = ascii.read('spectra.dat')

model = NirdustSpectrum(T=12, z=0.4, fitter='LevMarq')
model.fit(data['wave'], data['flux'], data['fluxErr'])
print(model.params['T'], model.params['z'])

fluxes = model.sample(wave=np.range(3000, 12000)) 
```
