### ISSUE TITLE
Documentacion sin sentido

### ISSUE THREAD

**Issue by leliel12** [Gaiana/nirdust#19]
https://github.com/Gaiana/nirdust/blob/2a6b1ee9d3a960f554754c9d49ed72909b296cdf/nirdust.py#L50-L51

**Comment by leliel12** [comment]
esa documentacion suele ponerse como la  operacion equivalente

`x.__getattr__(b) `es lo mismo que` getattr(x, "b")`

ver: https://github.com/quatrope/uttrs/blob/43ea852ece469fd9983ea96e48429e2bfef7203e/uttr.py#L274-L288

**Comment by j0sealacoria** [comment]
Close
