### ISSUE TITLE
Muchos metodos privados

### ISSUE THREAD

**Issue by leliel12** [Gaiana/nirdust#22]
La clase NirdustSpectrum tiene la mayoria de metodos privados. Esto hace pensar en su utilidad.

Por que todo es privado?

Esto puede ser un [code smell](https://en.wikipedia.org/wiki/Code_smell)

Por favor leer: https://carlosschults.net/en/are-private-methods-a-code-smell/

**Comment by leliel12** [comment]
Si para vos esta todo ok cerralo

**Comment by Gaiana** [comment]
solved
