### ISSUE TITLE
testing de empaquetado

### ISSUE THREAD

**Issue by leliel12** [Gaiana/nirdust#24]
Los archivos MANIFEST.in controlan el contenido de los paquetes binarios en python.

Por ejemplo controlan que no se agrgegue toda la documentacion, pero si la licencia al paquete (importante por cuestiones legales)

Agregar el environment de test siguiente a tox (y travis)

```ini
[testenv:check-manifest]
skip_install = True
usedevelop = False
deps = check-manifest
commands =
    check-manifest
```

Puede crearse un archivo MANIFEST vacio con `check-manifest -c` es importante tener en cuenta que para que todo funcione tienen que hacer `git add MANIFEST.in`

> Ver MANIFEST.in de pyedra

**Comment by j0sealacoria** [comment]
Ready
