### ISSUE TITLE
Remove extension as argument

### ISSUE THREAD

**Issue by mchalela** [Gaiana/nirdust#36]
Remove the fits extension as argument. It should be detected automatically with other header cards.
https://github.com/Gaiana/nirdust/blob/76d8591300afe43dcf6d6ff87191f91184064040/nirdust.py#L456-L457

**Comment by leliel12** [comment]
+1

**Comment by mchalela** [comment]
This answer shows how to use the header with astropy and how to compute the spectral axis.
https://astronomy.stackexchange.com/questions/43552/working-with-stellar-spectra-in-fits-format-in-python

The header keywords are recognized automatically by the WCS. If we can implement this, the header keywords won't be needed as arguments for `read_spectrum` and the API will be simpler.
@Gaiana @leliel12 @j0sealacoria
